# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 03 Feb 2019 21:25:59 +0000
*               @ALL          0
*               @user         8
