<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: mrsalta
 * Date: Sun, 03 Feb 2019 22:52:12 +0000
 */

$conf['title'] = 'Emmaverse Wiki';
$conf['start'] = 'emmaverse_home';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'flatly';
$conf['tpl']['bootstrap3']['showThemeSwitcher'] = 1;

// end auto-generated content
